### ISSUE TITLE
Research Uploadcare

### ISSUE THREAD

**Issue by johnson-rl** [Vedelopment/learning-hub#49]
- [ ] Determine if it's a better solution than paperclip

**Comment by mblair415** [comment]
Also consider Carrierwave

**Comment by mblair415** [comment]
These are terrible instructions:
https://uploadcare.com/quick_start/

These are bad instructions:
https://github.com/uploadcare/uploadcare-ruby

These are better instructions:
https://github.com/uploadcare/uploadcare-rails


None of that matters.  I can't follow any of it.
