### ISSUE TITLE
D3 - console errors 

### ISSUE THREAD

**Issue by mblair415** [Vedelopment/learning-hub#78]
D3 - console errors

**Comment by Vedelopment** [comment]
Had to change $.get to $.ajax type call. Unclear why this cleared the problem. $.get would function properly but show console errors regardless of it functioning properly.

http://stackoverflow.com/questions/24494632/how-to-create-d3-graph-using-data-from-rails-database

**Comment by Vedelopment** [comment]
Had to change $.get to $.ajax type call. Unclear why this cleared the problem. $.get would function properly but show console errors regardless of it functioning properly.

http://stackoverflow.com/questions/24494632/how-to-create-d3-graph-using-data-from-rails-database
