### ISSUE TITLE
Restyle Profile Pages (Teacher and Student) so that columns line up properly

### ISSUE THREAD

**Issue by johnson-rl** [Vedelopment/learning-hub#90]
Contact Info doesn't line up if any of the text wraps.

The same is probably true for the assigments/submissions/feedbacks section of the card on the right.

**Comment by Vedelopment** [comment]
![image](https://cloud.githubusercontent.com/assets/22309434/24364673/5e10b73e-12c8-11e7-83ec-4cf700bf3b92.png)
